contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ttmap channel"
    url: https://nfcore.slack.com/channels/ttmap
    about: Discussion about the m-mahgoub/ttmap pipeline
